### PR TITLE
Address comments 

### PR DESCRIPTION
**Pull request by llrs**
This PR address the points raised on #19 and other comments received. It doesn't address #8 (I think it would be to push for too much). 

- Moves the motivation to write this letter and the call for support from the letter to the README of the repository. Effectively focusing only on the petitions
- It changes the introduction to highlight the role that CRAN plays on the R system.
- I modified the petitions, merging 2 and adding a new one about CRAN policies. (I think it made sense)
- The petitions are now supported by a paragraph or two with proposed solutions and examples of how would this help CRAN and R packages developers.

### CODE REVIEW

**Comment by MilesMcBain** [comment]
Thanks for your efforts @llrs!

I am also currently working on a new draft that incorporates the feedback we have received and borrows your idea of breaking out rationale under each reform.

**Comment by llrs** [comment]
Not sure how to interpret this. You already provided private feedback on the modifications I made. 
I hope this PR will be merged and you can continue building upon it.

**Comment by MilesMcBain** [comment]
The main feedback I provided was that the introduction section was too long and repetitive. This has not been addressed. It could probably be cut to 50% of its current length and still make the same points.

**Comment by llrs** [comment]
Now is more or less half of what it was. Any other issues I should fix?

**Comment by MilesMcBain** [comment]
Thanks that's an improvement, thankyou.

The other issue I have with the introduction in this version is that it doesn't really motivate the reforms. Some of that is now attached to the reforms themselves, but the introduction could flag the core issue at a high level. For example, this is what I have in my current draft:

> In particular there appears to be pattern of increasingly unreliable criteria coupled with authoritarian practices that is adding to the burden on both package contributors and CRAN administrators.

>This pattern is driving behavioural change in contributors among us. Many are acting to reduce their exposure to CRAN's policies and checks. This not only undermines CRAN's checking system but also the R language itself since CRAN checks are used to validate core changes.

>There are also contributors for whom the increasing burden has reached a tipping point, leading them to feel frustrated and discouraged. There is evidence that this frustration is mirrored by some CRAN administrators with numerous accounts of communications that are apparently coloured by it.
 
It still needs a lot of revision, but it captures my idea for now. Hopefully see what it's trying to do: Outline the core of the issues.

**Comment by llrs** [comment]
I added a paragraph flagging the core issue at a very high level: a communication problem.

I also modified some of the reforms, to make clear that R journal issues are not enough as a notification if CRAN policy are enforced before. 

Is there anything else you think could be modified before merging?

**Comment by MilesMcBain** [comment]
The root cause as communication?

I'll have to think about that one. Not sure I agree. Lack communication is certainly a huge part of it and I agree most of the fixes are oriented that way.

Why is CRAN seemingly making the criteria tighter and enforcing them with archive threats and bans?

To me it's also probably about time in a big way. They don't have the time to deal with packages on a case by case basis, so they're just throwing things off because computer says fail. Shifting burden onto contributors. This suggests a root cause of scale and lack of resources.

The problem is they almost certainly need better communication to attract more resources.

Hmmmmmmmmm.

I'll be traveling for the next couple of days and will be thinking about this and your draft. More comments when I get back.

**Comment by llrs** [comment]
> Why is CRAN seemingly making the criteria tighter and enforcing them with archive threats and bans?

CRAN hasn't explained the reasons so I'm not sure. But I think CRAN is always making the criteria tighter: they cannot make it looser as this would mean wasted time and less quality package for all. About archive bans, the only "leverage" CRAN controls is what is inside CRAN. Is the only way they have to prevent/delay someone to share a package that does not meet the(ir) quality standards. What else can they do? They can't forbid you to develop it or prevent you to distribute it somewhere else (r-universe, github, mailing list, ...), it would be absurd. 

Certainly reviewing around 300 new packages every month is very hard. That's why the automatic checks help to only manually inspect those packages that pass them. Note, that Bioconductor and rOpenSci require that all package submissions pass the automatic checks before the reviewers look at the code too and have been also pushing for tighter criteria too (albeit only on submissions and not on already accepted packages). For example, new packages on Bioconductor can't have the .github folder or similar files even if they are on .Rbuildignore, while previously this was possible. 

There might be a resource shortage on CRAN. But what resources do you think are need to make faster and better reviews? And if you think this is the major reason, what can we do to help them remediate this?

**Comment by MilesMcBain** [comment]
I just pushed up a new draft.

When you read it, you will see that this draft and our conversations in this and other threads have been highly influential in its composition.

I don't mean to offend you by doing this, your efforts have been influential and appreciated. The main reasons I have done it this way are:

* I had already begun work on it before you made this PR and while the directions we were going we largely compatible, the writing styles were not.
* There are numerous English phrasings in your draft that are unusual to me. I don't pretend to be an expert, but reconciling all of them would have been a laborious process that probably would have ended in a substantial rewrite anyway. You will see I have borrowed a number via paraphrases.

**Comment by llrs** [comment]
I don't feel offended but very disappointed. Some comments below:

- Last feedback on this PR was that you would think about the root cause of CRAN problems and comment back. 
- The commits show a date later than when I started working on these modifications. The commits date start the same day I opened this PR. Not that it really matters who was first, but is relevant for the next point you raise.
- Yes, probably English on this draft should be polished, feedback from the beginning about it and corrections as I was modifying the letter could have helped avoiding a substantial rewrite. 

This PR is obsolete given that #22 has been opened and merged, I'm closing it. 

I might write my concerns about the new draft on separated issues.

**Pull request closed without merging**
